package com.verifone.drools

import  com.verifone.drools.service.Passport;
import  com.verifone.drools.service.Validation;


rule "Expired"
  dialect "java"
  when
	$passport: Passport(isExpired())
  then
	System.out.println($passport+" This passport is INVALID because it is expired");
	$passport.setValidation(Validation.FAILED);
end

rule "full passport"
  dialect "java"
  when
	$passport: Passport(unusedVisaPages == 0 )
  then
	System.out.println($passport+" This passport is INVALID because it has no space for visa" );
	$passport.setValidation(Validation.FAILED);
end

// built a rule based on the above Validation setter consideration
rule "Valid passport"
  dialect "java"
  when
	$passport: Passport(validation == Validation.UNKNOWN)
  then
	System.out.println($passport+" This passport is CORRECT ");
	$passport.setValidation(Validation.PASSED);
end
