package com.verifone.drools

import  com.verifone.drools.service.Passport;

rule "Valid passport"
  dialect "java"
  when
	$passport: Passport( !isExpired() &&  $unUsedPages : unusedVisaPages > 0 )
  then
	System.out.println($passport+" This passport is CORRECT, It have pages "+$unUsedPages);
end

rule "Expired"
  dialect "java"
  when
	$passport: Passport(isExpired())
  then
	System.out.println($passport+" This passport is INVALID because it is expired");
end

rule "full passport"
  dialect "java"
  when
	$passport: Passport(unusedVisaPages == 0 )
  then
	System.out.println($passport+" This passport is INVALID because it has no space for visa" );
end
